# -*- coding: utf-8 -*-
"""PINNs-FluidDny.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASDtou2xALrcdb2hLJRcdewbW8cARtcM

#Imports
"""

import torch
import torch.nn as nn
import torch.optim as opt
import numpy as np
import matplotlib.pyplot as plt
import math
torch.manual_seed(10)
np.random.seed(10)
print(f"Torch version : {torch.__version__}")

"""#Data Generation

"""

#Data set 1 : Initial condition data ( initial condition where time(t) = 0 the velocity of fluid is u = -sin(Pi*x))
N_ic = 2000
x_ic = torch.linspace(-1.0,1.0,N_ic).view(-1,1)
t_ic = torch.zeros(N_ic , 1)
u_ic = -torch.sin(torch.pi*x_ic)


#Data set 2 : Boundary conditions where x = -1 and x = 1 the velocity of the fluid is u = 0
N_bc = 1000
#Left wall (x=-1)
x_bc_left = -torch.ones(N_bc,1)
t_bc_left = torch.rand(N_bc,1)
u_bc_left = torch.zeros(N_bc,1)
#Right wall (x=`)
x_bc_right = torch.ones(N_bc,1)
t_bc_right = torch.rand(N_bc,1)
u_bc_right = torch.zeros(N_bc,1)

#Combining both the right and left walls to be one Boundary Condition
x_bc = torch.cat([x_bc_left,x_bc_right], dim =0)
t_bc = torch.cat([t_bc_left,t_bc_right], dim=0)
u_bc = torch.cat([u_bc_left,u_bc_right],dim=0)

#Data set 3: Interior points
N_in = 10000
x_in = (torch.rand(N_in,1)*2.0)-1.0
t_in = torch.rand(N_in,1)
x_in.requires_grad_(True)
t_in.requires_grad_(True)

"""#PINNs Architecture"""

class BurgersPDE(nn.Module):
  def __init__(self):
    super(BurgersPDE,self).__init__()

    self.network = nn.Sequential(
        nn.Linear(2,32),
        nn.Tanh(),
        nn.Linear(32,32),
        nn.Tanh(),
        nn.Linear(32,32),
        nn.Tanh(),
        nn.Linear(32,1)
    )

  def forward(self,x,t):
    combined_input = torch.cat([x,t],dim=1)
    return self.network(combined_input)


  def PDE_LOSS(self,x,t, viscosity = 0.01/math.pi):
    u = self.forward(x,t)

    #finding the du/dx and du/dt

    u_x = torch.autograd.grad(
        outputs = u,
        inputs = x,
        grad_outputs=torch.ones_like(u),
        create_graph=True
    )[0]

    u_t = torch.autograd.grad(
        outputs=u,
        inputs = t,
        grad_outputs = torch.ones_like(u),
        create_graph = True
    )[0]

    # Finding the second derivative which is friction
    u_xx = torch.autograd.grad(
        outputs=u_x,
        inputs=x,
        grad_outputs = torch.ones_like(u_x),
        create_graph=True
    )[0]

    equation = u_x+ u*u_t - viscosity*u_xx
    return torch.mean(equation**2)

"""#Training"""

model = BurgersPDE()
optimizer = opt.Adam(model.parameters(), lr = 0.001)
mse_loss = nn.MSELoss()

epochs = 10000
print("Training the model ...")
for epoch in range(epochs):
  optimizer.zero_grad()

  #Check the start line error
  u_pred_ic = model(x_ic,t_ic)
  loss_ic = mse_loss(u_pred_ic , u_ic)

  #Check the boundar condition error
  u_pred_bc = model(x_bc , t_bc)
  loss_bc = mse_loss(u_pred_bc, u_bc)

  #check the physics law violation loss
  loss_PDE  = model.PDE_LOSS(x_in,t_in)


  total_loss = loss_ic + loss_bc + 2*loss_PDE
  total_loss.backward()
  optimizer.step()

  if epoch % 1000 == 0:
    print(f"Epoch : {epoch} | Total Loss : {total_loss.item()} | PDE_Loss : {loss_PDE.item()}")

torch.save(model.state_dict(), "burgers_pinns_weights.pth")
print("Training completed . Weights saved sucessfully as burgers_pinns_weights.pth")

"""#Domain Visualization"""

from matplotlib.lines import lineStyles
plt.figure(figsize=(10,6))

plt.scatter(
    t_in.detach().numpy()[:1000],
    x_in.detach().numpy()[:1000],
    c = 'lightgray',
    marker = 'x',
    alpha = 0.6,
    label = "Interior Physics Pins"
)

plt.scatter(
    t_ic.detach().numpy(),
    x_ic.detach().numpy(),
    c = 'blue',
    marker = 'o',
    s = 15,
    label = 'Initial Condition (t=0)'
)

plt.scatter(
    t_bc.detach().numpy(),
    x_bc.detach().numpy(),
    c = 'red',
    s = 15,
    label = 'Boundary Condition (x= -1 ,1 )'
)

plt.title(
    "1D-Burgers Equation : Training Domain",
    fontsize = 14,
    fontweight = 'bold'
)

plt.xlabel("Time(t)", fontsize = 12)
plt.ylabel("Space(x)",fontsize = 12)
plt.legend(loc = "center right", bbox_to_anchor = (1.4,0.5))
plt.grid(True, linestyle = "--", alpha=0.5)
plt.savefig('PINNs_collocation_points.png', dpi = 300, bbox_inches = 'tight')
plt.show()

"""#SPATIO-TEMPORAL SHOCKWAVE HEATMAP"""

import numpy as np
import matplotlib.pyplot as plt
import torch


x_flat = np.linspace(-1, 1, 100)
t_flat = np.linspace(0, 1, 100)
T_grid, X_grid = np.meshgrid(t_flat, x_flat)


x_tensor = torch.tensor(X_grid.flatten(), dtype=torch.float32).view(-1, 1)
t_tensor = torch.tensor(T_grid.flatten(), dtype=torch.float32).view(-1, 1)


model.eval()
with torch.no_grad():
    u_pred_flat = model(x_tensor, t_tensor).numpy()


    U_pred_grid = u_pred_flat.reshape(X_grid.shape)


    plt.figure(figsize=(10, 6))


    contour = plt.contourf(T_grid, X_grid, U_pred_grid, levels=100, cmap='jet')
    plt.colorbar(contour, label='Fluid Velocity (u)')

    plt.title("PINN Prediction: Shockwave Formation", fontsize=14, fontweight='bold')
    plt.xlabel("Time (t)", fontsize=12)
    plt.ylabel("Space (x)", fontsize=12)


    plt.axhline(0, color='white', linestyle='--', alpha=0.8, label="Shock Front (x=0)")
    plt.legend(loc="upper right")

    plt.savefig("pinn_shockwave_heatmap.png", dpi=300, bbox_inches='tight')
    plt.show()